info:
  component: Configurations Services - ${PORT:8888}

server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL}/config-repo
          skip-ssl-validation: true
